CREATE USER wso2master WITH PASSWORD 'wso2master' CREATEDB;
CREATE USER wso2userstore WITH PASSWORD 'wso2userstore' CREATEDB;
CREATE DATABASE wso2master WITH OWNER wso2master;
CREATE DATABASE wso2userstore WITH OWNER wso2userstore;


\c wso2master;
CREATE ROLE wso2_master;
GRANT USAGE, CREATE ON SCHEMA public TO wso2_master;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO wso2_master;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO wso2_master;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO wso2_master;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO wso2_master;
GRANT wso2_master TO wso2master;

\c wso2userstore;
CREATE ROLE wso2_userstore;
GRANT USAGE, CREATE ON SCHEMA public TO wso2_userstore;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO wso2_userstore;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO wso2_userstore;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO wso2_userstore;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE ON SEQUENCES TO wso2_userstore;
GRANT wso2_userstore TO wso2userstore;
