DROP DATABASE IF EXISTS `wso2is_analytics`;
DROP DATABASE IF EXISTS `wso2carbon`;
DROP DATABASE IF EXISTS `wso2is_analytics_metrics`;

CREATE DATABASE `wso2is_analytics`;
CREATE DATABASE `wso2carbon`;
CREATE DATABASE `wso2is_analytics_metrics`;

USE `wso2is_analytics_metrics`;

CREATE TABLE IF NOT EXISTS METRIC_GAUGE (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SOURCE VARCHAR(255) NOT NULL,
    TIMESTAMP BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    VALUE VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS METRIC_COUNTER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SOURCE VARCHAR(255) NOT NULL,
    TIMESTAMP BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    COUNT BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS METRIC_METER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SOURCE VARCHAR(255) NOT NULL,
    TIMESTAMP BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    COUNT BIGINT NOT NULL,
    MEAN_RATE DECIMAL NOT NULL,
    M1_RATE DECIMAL NOT NULL,
    M5_RATE DECIMAL NOT NULL,
    M15_RATE DECIMAL NOT NULL,
    RATE_UNIT VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS METRIC_HISTOGRAM (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SOURCE VARCHAR(255) NOT NULL,
    TIMESTAMP BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    COUNT BIGINT NOT NULL,
    MAX DECIMAL NOT NULL,
    MEAN DECIMAL NOT NULL,
    MIN DECIMAL NOT NULL,
    STDDEV DECIMAL NOT NULL,
    P50 DECIMAL NOT NULL,
    P75 DECIMAL NOT NULL,
    P95 DECIMAL NOT NULL,
    P98 DECIMAL NOT NULL,
    P99 DECIMAL NOT NULL,
    P999 DECIMAL NOT NULL
);

CREATE TABLE IF NOT EXISTS METRIC_TIMER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    SOURCE VARCHAR(255) NOT NULL,
    TIMESTAMP BIGINT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    COUNT BIGINT NOT NULL,
    MAX DECIMAL NOT NULL,
    MEAN DECIMAL NOT NULL,
    MIN DECIMAL NOT NULL,
    STDDEV DECIMAL NOT NULL,
    P50 DECIMAL NOT NULL,
    P75 DECIMAL NOT NULL,
    P95 DECIMAL NOT NULL,
    P98 DECIMAL NOT NULL,
    P99 DECIMAL NOT NULL,
    P999 DECIMAL NOT NULL,
    MEAN_RATE DECIMAL NOT NULL,
    M1_RATE DECIMAL NOT NULL,
    M5_RATE DECIMAL NOT NULL,
    M15_RATE DECIMAL NOT NULL,
    RATE_UNIT VARCHAR(50) NOT NULL,
    DURATION_UNIT VARCHAR(50) NOT NULL
);

CREATE INDEX IDX_TIMESTAMP_GAUGE ON METRIC_GAUGE (TIMESTAMP);
CREATE INDEX IDX_TIMESTAMP_COUNTER ON METRIC_COUNTER (TIMESTAMP);
CREATE INDEX IDX_TIMESTAMP_METER ON METRIC_METER (TIMESTAMP);
CREATE INDEX IDX_TIMESTAMP_HISTOGRAM ON METRIC_HISTOGRAM (TIMESTAMP);
CREATE INDEX IDX_TIMESTAMP_TIMER ON METRIC_TIMER (TIMESTAMP);
