version: '2.3'
services:
  mysql:
    image: mysql:5.7.19
    ports:
      - 3306
    environment:
        MYSQL_ROOT_PASSWORD: wso2carbon
    volumes:
      - ./mysql/scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-pwso2carbon"]
      interval: 5s
      timeout: 60s
  identity-server-1:
    image: wso2is:5.3.0
    ports:
      - 4000
      - 9763
      - 9443
    healthcheck:
        test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
        interval: 5s
        timeout: 120s
        start_period: 120s
    environment:
      - EXCLUDE_PORTS=4000,9763
      - VIRTUAL_HOST=https://wso2is
      - EXTRA_ROUTE_SETTINGS=ssl check verify none
      - BALANCE=source
    volumes:
        - ./identity-server/repository/components/lib/mysql-connector-java-5.1.34-bin.jar:/home/wso2carbon/wso2is-5.3.0/repository/components/lib/mysql-connector-java-5.1.34-bin.jar
        - ./identity-server/repository/conf/carbon.xml:/home/wso2carbon/wso2is-5.3.0/repository/conf/carbon.xml
        - ./identity-server/repository/conf/axis2/axis2-1.xml:/home/wso2carbon/wso2is-5.3.0/repository/conf/axis2/axis2.xml
        - ./identity-server/repository/conf/datasources/master-datasources.xml:/home/wso2carbon/wso2is-5.3.0/repository/conf/datasources/master-datasources.xml
        - ./identity-server/repository/conf/tomcat/catalina-server.xml:/home/wso2carbon/wso2is-5.3.0/repository/conf/tomcat/catalina-server.xml
    depends_on:
      mysql:
        condition: service_healthy
    links:
        - mysql
  identity-server-2:
    image: wso2is:5.3.0
    ports:
      - 4000
      - 9763
      - 9443
    healthcheck:
        test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/carbon/admin/login.jsp"]
        interval: 5s
        timeout: 120s
        start_period: 120s
    environment:
      - EXCLUDE_PORTS=4000,9763
      - VIRTUAL_HOST=https://wso2is
      - EXTRA_ROUTE_SETTINGS=ssl check verify none
      - BALANCE=source
    volumes:
        - ./identity-server/repository/components/lib/mysql-connector-java-5.1.34-bin.jar:/home/wso2carbon/wso2is-5.3.0/repository/components/lib/mysql-connector-java-5.1.34-bin.jar
        - ./identity-server/repository/conf/carbon.xml:/home/wso2carbon/wso2is-5.3.0/repository/conf/carbon.xml
        - ./identity-server/repository/conf/axis2/axis2-2.xml:/home/wso2carbon/wso2is-5.3.0/repository/conf/axis2/axis2.xml
        - ./identity-server/repository/conf/datasources/master-datasources.xml:/home/wso2carbon/wso2is-5.3.0/repository/conf/datasources/master-datasources.xml
        - ./identity-server/repository/conf/tomcat/catalina-server.xml:/home/wso2carbon/wso2is-5.3.0/repository/conf/tomcat/catalina-server.xml
    depends_on:
      mysql:
        condition: service_healthy
      identity-server-1:
        condition: service_healthy
    links:
        - mysql
  haproxy:
    image: dockercloud/haproxy:1.6.3
    ports:
      - 443:443
    environment:
      - TIMEOUT=connect 50000, client 50000, server 50000
      - STATS_AUTH=stats:stats
      - CERT_FOLDER=/certs/
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./haproxy/cert1.pem:/certs/cert1.pem
    depends_on:
      identity-server-2:
        condition: service_healthy
    links:
      - identity-server-1
      - identity-server-2