[server]
hostname = "localhost"
node_ip = "127.0.0.1"
base_path = "https://$ref{server.hostname}:${carbon.management.port}"

[super_admin]
username = "admin"
password = "admin"
create_admin_account = true

[user_store]
type = "database_unique_id"
scim_enabled = "true"

[database.identity_db]
type = "postgre"
hostname = "postgre"
name = "wso2master"
username = "wso2master"
password = "wso2master"
port = "5432"

[database.identity_db.pool_options]
maxActive = "20"
maxWait = "60000"
minIdle = "5"
testOnBorrow = true
validationQuery="SELECT 1; COMMIT"
validationInterval="30000"
defaultAutoCommit=false


[database.shared_db]
type = "postgre"
hostname = "postgre"
name = "wso2master"
username = "wso2master"
password = "wso2master"
port = "5432"

[database.shared_db.pool_options]
maxActive = "20"
maxWait = "60000"
minIdle = "5"
testOnBorrow = true
validationQuery="SELECT 1; COMMIT"
validationInterval="30000"
defaultAutoCommit=false

[database.user]
url = "jdbc:postgresql://postgre:5432/wso2master?autoReconnect=true"
username = "wso2master"
password = "wso2master"
driver = "org.postgresql.Driver"

[database.user.pool_options]
maxActive = "20"
maxWait = "60000"
minIdle = "5"
testOnBorrow = true
validationQuery="SELECT 1; COMMIT"
validationInterval="30000"
defaultAutoCommit=false

# wso2 ticket created. Until it resolves keep these lines commented out.
#[bps_database.config]
#url = "jdbc:postgresql://postgre:5432/wso2master?autoReconnect=true"
#username = "wso2master"
#password = "wso2master"
#driver = "org.postgresql.Driver"

[authentication.consent]
prompt="false"


#[keystore.primary]
#name = "wso2carbon.jks"
#password = "wso2carbon"

[identity_mgt.account_disabling]
enable_account_disabling = "true"

[session_data.persistence]
enable_persistence = false

[admin_service.wsdl]
enable = true
